apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-01-cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: platform-stg
  source:
    repoURL: https://github.com/litomi2026/litomi-gitops.git
    targetRevision: main
    path: apps/platform/cloudflared/overlays/stg
  destination:
    name: stg-01
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
