apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-01-longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: platform-workload
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.11.1
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/apps/platform/longhorn/values.yaml
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      ref: values
  destination:
    name: stg-01
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
