apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: litomi-stg
spec:
  description: Litomi staging workload
  sourceRepos:
    - https://github.com/litomi2026/litomi-gitops.git
  destinations:
    - name: stg-01
      namespace: litomi
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
  permitOnlyProjectScopedClusters: true
