fullnameOverride: redis

architecture: standalone

auth:
  enabled: true
  existingSecret: litomi-backend-secret
  existingSecretPasswordKey: REDIS_PASSWORD
  usePasswordFiles: true
  usePasswordFileFromSecret: true

primary:
  priorityClassName: litomi-runtime
  startupProbe:
    enabled: true
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 3
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: valkey
          app.kubernetes.io/instance: redis
  pdb:
    create: false
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

metrics:
  enabled: false

networkPolicy:
  enabled: false
