fullnameOverride: redis-ha

architecture: replication

auth:
  enabled: false

sentinel:
  enabled: true
  quorum: 2
  primarySet: litomi
  service:
    createPrimary: false

primary:
  podAntiAffinityPreset: soft
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

replica:
  replicaCount: 2
  podAntiAffinityPreset: soft
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: valkey
          app.kubernetes.io/instance: redis-ha
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: kube-prometheus-stack
      app.kubernetes.io/instance: kube-prometheus-stack

networkPolicy:
  enabled: false
