apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - applications/core.yaml
  - applications/redis.yaml
  - applications/backend.yaml
  - applications/web.yaml
  - applications/edge.yaml
