apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-01-minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  project: platform-mgmt
  sources:
    - repoURL: https://operator.min.io
      chart: tenant
      targetRevision: 7.1.1
      helm:
        releaseName: tenant
        valueFiles:
          - $values/apps/platform/minio/tenant.values.yaml
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      path: clusters/mgmt-01/central-services/minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
