apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-01-velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '6'
spec:
  project: platform-mgmt
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 12.0.0
      helm:
        releaseName: velero
        valueFiles:
          - $values/apps/platform/velero/velero.values.yaml
          - $values/clusters/mgmt-01/ops/velero/values.yaml
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      path: clusters/mgmt-01/ops/velero
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
