apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-minio
  namespace: logging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: loki-minio
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: access_key
      remoteRef:
        key: clusters/prod-01/logging/loki-s3
        property: access_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret_key
      remoteRef:
        key: clusters/prod-01/logging/loki-s3
        property: secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: bucket_chunks
      remoteRef:
        key: clusters/prod-01/logging/loki-s3
        property: bucket_chunks
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: bucket_ruler
      remoteRef:
        key: clusters/prod-01/logging/loki-s3
        property: bucket_ruler
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
