loki:
  limits_config:
    retention_period: 336h

singleBinary:
  persistence:
    size: 40Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
