apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-01-gtm-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: public-edge
  source:
    repoURL: https://github.com/litomi2026/litomi-gitops.git
    targetRevision: main
    path: clusters/stg-01/addons/public-edge/gtm-server
  destination:
    name: stg-01
    namespace: gtm-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
