apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - applications/longhorn.yaml
  - applications/metallb.yaml
  - applications/traefik.yaml
  - applications/external-secrets.yaml
  - applications/metrics-server.yaml
  - applications/monitoring.yaml
  - applications/loki.yaml
  - applications/fluent-bit.yaml
  - applications/tempo.yaml
  - applications/otel-collector.yaml
  - applications/velero.yaml
