apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi

resources:
  - ../../../../apps/litomi/backend
  - configmap-litomi-backend-env.yaml
  - hpa-backend.yaml

images:
  - name: litomi-backend
    newName: ghcr.io/litomi2026/litomi-backend
    digest: sha256:786ffc13ccb3225d6cac4e9d7950d15f937fbb0d656df2730e70df5b2a798968
