apiVersion: apps/v1
kind: Deployment
metadata:
  name: litomi-web
spec:
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1280Mi
