apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - applications/monitoring.yaml
  - applications/loki.yaml
  - applications/tempo.yaml
  - applications/otel-collector.yaml
  - applications/fluent-bit.yaml
  - applications/velero.yaml
