apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi

resources:
  - ../../base
  - hpa-web.yaml
  - configmap-litomi-web-env.yaml

images:
  - name: litomi-web
    newName: ghcr.io/litomi2026/litomi-web
    digest: sha256:fb275497245d1cdd71c6a8337a339deafa14ddc39ec391f976ed8b1bdd3a717a
