apiVersion: v1
kind: ConfigMap
metadata:
  name: litomi-public-edge-public-env
data:
  NEXT_PUBLIC_API_ORIGIN: https://api.litomi.in
  NEXT_PUBLIC_EDGE_PROXY_ORIGIN: https://vercel.litomi.in
  NEXT_PUBLIC_EDGE_PROXY_NEW_ORIGIN: https://vercel2.litomi.in
  NEXT_PUBLIC_IMAGE_PROXY_ORIGIN: https://img.litomi.in
  NEXT_PUBLIC_GTM_ID: GTM-TRJSRS73
  NEXT_PUBLIC_GTM_SCRIPT_URL: https://anal.litomi.in/gtm.js
