apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi

resources:
  - configmap-litomi-public-edge-common-env.yaml
  - configmap-litomi-public-edge-public-env.yaml
  - ingress.yaml
