apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-env-configuration
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: minio-env-configuration
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        config.env: |-
          export MINIO_ROOT_USER={{ .root_user }}
          export MINIO_ROOT_PASSWORD={{ .root_password }}
  data:
    - secretKey: root_user
      remoteRef:
        key: clusters/mgmt-01/minio/minio-root
        property: root_user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: root_password
      remoteRef:
        key: clusters/mgmt-01/minio/minio-root
        property: root_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
