apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi

resources:
  - ../../../../apps/litomi/shared
  - configmap-litomi-common-env.yaml
  - configmap-litomi-public-env.yaml
  - priorityclass-litomi-runtime.yaml
  - secretstore-vault.yaml
  - externalsecret-litomi-backend-secret.yaml
