apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-01-public-edge-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: public-edge
  source:
    repoURL: https://github.com/litomi2026/litomi-gitops.git
    targetRevision: main
    path: clusters/prod-01/addons/public-edge/monitoring
  destination:
    name: prod-01
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
