apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: tracing
spec:
  provider:
    vault:
      server: https://vault.mgmt.litomi.internal
      path: kv
      auth:
        kubernetes:
          mountPath: k8s-stg-01
          role: eso-tracing
          serviceAccountRef:
            name: eso-vault
            audiences:
              - vault
      caProvider:
        type: ConfigMap
        name: vault-ca
        key: ca.crt
