grafana:
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki.logging.svc:3100
      isDefault: false
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.tracing.svc:3200
      isDefault: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: -5m
          spanEndTimeShift: 5m
          filterByTraceID: true
          filterBySpanID: false

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi

prometheus:
  prometheusSpec:
    externalLabels:
      cluster: prod-01
    retention: 15d
    retentionSize: 40GiB
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi
