apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: cloudflared-token
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: token
      remoteRef:
        key: clusters/prod-01/cloudflared/cloudflared-token
        property: token
