apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount-backend.yaml
  - configmap-backend-google-credentials.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - networkpolicy-backend-ingress.yaml
