apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi

resources:
  - ../../../../apps/litomi/web
  - configmap-litomi-web-env.yaml
  - hpa-web.yaml

patches:
  - path: patch-deployment-resources.yaml

images:
  - name: litomi-web
    newName: ghcr.io/litomi2026/litomi-web
    digest: sha256:00c579dd75b0e07ac87f83e091c362492b248da52cbc8c970029061b88dcb429
