apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi

resources:
  - ../../../../apps/litomi/web
  - configmap-litomi-web-env.yaml
  - hpa-web.yaml

patches:
  - path: patch-deployment-resources.yaml

images:
  - name: litomi-web
    newName: ghcr.io/litomi2026/litomi-web
    digest: sha256:83d85334836fa442bf91d181578e5923eb048b4e2117bf98329b254ed92f2ae0
