apiVersion: apps/v1
kind: Deployment
metadata:
  name: litomi-web
spec:
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              cpu: 40m
              memory: 384Mi
            limits:
              cpu: 120m
              memory: 512Mi
