apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-01-fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '4'
spec:
  project: platform-workload
  sources:
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: 0.57.2
      helm:
        releaseName: fluent-bit
        valueFiles:
          - $values/apps/platform/logging/fluent-bit.values.yaml
          - $values/clusters/prod-01/ops/logging/fluent-bit.values.yaml
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      ref: values
  destination:
    name: prod-01
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
