apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-01-minio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: platform-prod
  sources:
    - repoURL: https://operator.min.io
      chart: operator
      targetRevision: 7.1.1
      helm:
        releaseName: minio-operator
        valueFiles:
          - $values/apps/platform/minio/base/operator.values.yaml
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      ref: values
  destination:
    name: prod-01
    namespace: minio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
