apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-01-tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  project: platform-workload
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.24.4
      helm:
        releaseName: tempo
        valueFiles:
          - $values/apps/platform/tracing/tempo.values.yaml
          - $values/clusters/prod-01/ops/tracing/tempo.values.yaml
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      path: clusters/prod-01/ops/tracing
  destination:
    name: prod-01
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
