apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-01-traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: platform-workload
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 39.0.7
      helm:
        releaseName: traefik
        valueFiles:
          - $values/apps/platform/traefik/values.yaml
    - repoURL: https://github.com/litomi2026/litomi-gitops.git
      targetRevision: main
      ref: values
  destination:
    name: prod-01
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
