apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook-warning
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: alertmanager-discord-webhook-warning
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: url
      remoteRef:
        key: clusters/mgmt-01/monitoring/alertmanager-webhook-warning
        property: url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
