grafana:
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki.logging.svc:3100
      isDefault: false
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.tracing.svc:3200
      isDefault: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: -5m
          spanEndTimeShift: 5m
          filterByTraceID: true
          filterBySpanID: false

prometheus:
  prometheusSpec:
    externalLabels:
      cluster: mgmt-01
    retention: 15d
    retentionSize: 80GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 80Gi
