apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - projects/bootstrap-admin.yaml
  - projects/platform-mgmt.yaml
  - projects/platform-workload.yaml
  - projects/litomi-workload.yaml
  - projects/public-edge.yaml
  - appsets/platform-clusters.yaml
  - appsets/litomi-clusters.yaml
  - appsets/public-edge-addons.yaml
  - applications/mgmt-01.yaml
