apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-minio
  namespace: tracing
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: tempo-minio
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: access_key
      remoteRef:
        key: clusters/mgmt-01/tracing/tempo-s3
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: clusters/mgmt-01/tracing/tempo-s3
        property: secret_key
    - secretKey: bucket_traces
      remoteRef:
        key: clusters/mgmt-01/tracing/tempo-s3
        property: bucket_traces
