apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-01-litomi-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: litomi-prod
  source:
    repoURL: https://github.com/litomi2026/litomi-gitops.git
    targetRevision: main
    path: clusters/prod-01/litomi/backend
  destination:
    name: prod-01
    namespace: litomi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
