apiVersion: v1
kind: ResourceQuota
metadata:
  name: litomi-runtime
  namespace: litomi
spec:
  hard:
    pods: "30"
    services: "15"
    persistentvolumeclaims: "5"
    requests.cpu: "2"
    requests.memory: 6Gi
    limits.cpu: "6"
    limits.memory: 10Gi
    requests.storage: 30Gi
