apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - serviceaccount-eso-vault.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - networkpolicy-metrics-ingress.yaml

configMapGenerator:
  - name: vault-ca
    files:
      - ca.crt=../../../../bootstrap/pki/vault-ca.pem

images:
  - name: cloudflare/cloudflared
    newTag: 2026.1.2
