defaultSettings:
  defaultDataPath: /var/lib/longhorn
  replicaSoftAntiAffinity: true
  replicaAutoBalance: best-effort
  storageMinimalAvailablePercentage: 15

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: false

service:
  ui:
    type: ClusterIP

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
      app.kubernetes.io/instance: kube-prometheus-stack
