resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceMonitor:
  enabled: false
  metricsEndpoints:
    - port: metrics
      interval: 30s

alternateConfig:
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
  processors:
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
    batch: {}
    k8sattributes:
      auth_type: serviceAccount
  exporters:
    otlphttp/central:
      endpoint: http://otlp.mgmt.litomi.internal
  service:
    telemetry:
      metrics:
        readers:
          - pull:
              exporter:
                prometheus:
                  host: ${env:MY_POD_IP}
                  port: 8888
    extensions:
      - health_check
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - k8sattributes
          - batch
        exporters:
          - otlphttp/central
