apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi

resources:
  - ../../base
  - configmap-litomi-public-env.yaml
  - configmap-litomi-common-env.yaml
  - secretstore-vault.yaml
  - externalsecret-litomi-backend-secret.yaml
