apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi

resources:
  - ../../../../apps/litomi/backend
  - configmap-litomi-backend-env.yaml
  - hpa-backend.yaml

patches:
  - path: patch-deployment-resources.yaml

images:
  - name: litomi-backend
    newName: ghcr.io/litomi2026/litomi-backend
    digest: sha256:5fd70a772f12adf655b1192354c0ff727474458f024f483bd72c29d7b6130097
